stages: 
#  - test
  - build
#  - deploy


test project: 
  stage: test
  image: node:14
  script:
    - cd what2watch
    - cd frontend
    - yarn install
    - yarn test
    - yarn cypress:run

build project:
  stage: build
  image: node:14
  script:
    - cd frontend
    - yarn install
    - yarn build
