stages: 
  - test
  - build
#  - deploy


test project: 
  stage: test
  image: node:14
  script:
    - apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - cd frontend
    - yarn install
    - yarn test
    - yarn cypress:run:pipeline

build project:
  stage: build
  image: node:14
  script:
    - cd frontend
    - yarn install
    - yarn build
