stages: 
#  - test
  - build
#  - deploy


#test project: 
#  stage: test
#  image: node:14
#  script:
#    - cd gitlab-group-page
#    - yarn install
#    - yarn test -- --coverage --updateSnapshot

build project:
  stage: build
  image: node:14
  script:
    - cd frontend
    - yarn add "react-bootstrap/Container"
    - yarn install
    - yarn build
